In [51]:
# Importamos las librerías necesarias para el trabajo
import yahoo_finance as yahoo
import numpy as np
import pandas as pd
import datetime
from pandas_datareader import data

In [52]:
# Definimos las fechas que vamos a trabajar
start = datetime.datetime(2018,1,1)
end = datetime.datetime(2022,10,24)

In [53]:
# Colocamos las monedas de interés (principales economías del mundo)
list_of_tickers = ['USDAUD=X',,'USDARS=X','USDBRL=X','USDCAD=X','^TNX','USDCNY=X','USDCLP=X','USDCOP=X','USDHKD=X','USDHUF=X','USDIDR=X','USDINR=X','USDILS=X','USDJPY=X','USDKRW=X','USDMYR=X','USDMXN=X','USDPEN=X','USDPHP=X','USDPLN=X','USDCZK=X','USDRON=X','USDRUB=X','USDSAR=X','USDSGD=X','USDZAR=X','USDSEK=X','USDCHF=X','USDTWD=X','USDTHB=X','USDTRY=X','USDGBP=X','USDVND=X','USDEUR=X']

In [54]:
# Incorporamos lo predefinido para crear un dataframe
currencies = data.DataReader(list_of_tickers, 'yahoo', start, end)['Adj Close']

In [55]:
currencies

Symbols,USDAUD=X,USDARS=X,USDBRL=X,USDCAD=X,USDCNY=X,USDCLP=X,USDCOP=X,USDHKD=X,USDHUF=X,USDIDR=X,...,USDSGD=X,USDZAR=X,USDSEK=X,USDCHF=X,USDTWD=X,USDTHB=X,USDTRY=X,USDGBP=X,USDVND=X,USDEUR=X
Date,,,,,,,,,,,,,,,,,,,,,
2018-01-01,1.28170,19.087000,3.3076,1.25808,6.5057,613.500000,2936.000000,7.81360,258.670013,13542.000000,...,1.33700,12.319990,8.17990,0.97373,29.650999,31.855000,3.794900,0.73986,22325.0,0.83299
2018-01-02,1.28188,18.591000,3.3110,1.25550,6.5058,601.840027,2943.800049,7.81360,258.273010,13550.000000,...,1.33690,12.387000,8.17945,0.97472,29.773001,32.530998,3.791100,0.74012,22384.0,0.83253
2018-01-03,1.27650,18.390499,3.2578,1.25039,6.4940,606.000000,2891.800049,7.81630,256.108002,13496.000000,...,1.32906,12.435620,8.15690,0.97146,29.622000,32.410000,3.765600,0.73550,22378.0,0.82895
2018-01-04,1.27740,18.443501,3.2355,1.25469,6.5031,606.750000,2859.800049,7.81690,256.730011,13468.000000,...,1.33044,12.361000,8.18060,0.97714,29.593000,32.321999,3.780600,0.74012,22365.0,0.83261
2018-01-05,1.27165,18.614000,3.2331,1.24903,6.4933,605.299988,2849.800049,7.81760,255.080994,13415.000000,...,1.32680,12.287200,8.13209,0.97440,29.570000,32.227001,3.750270,0.73785,22419.0,0.82858
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
2022-10-18,1.58318,152.820297,5.2398,1.37262,7.2006,972.750000,4760.359863,7.84949,419.170013,15466.200195,...,1.41987,18.062099,11.07173,0.99368,32.016998,38.070000,18.579901,0.88150,24430.0,1.01380
2022-10-19,1.59650,153.167404,5.2692,1.37728,7.2273,973.700012,4838.259766,7.84920,423.570007,15620.000000,...,1.42579,18.196899,11.22479,1.00481,32.152000,38.299999,18.593100,0.89198,24450.0,1.02391
2022-10-20,1.59370,153.490891,5.2166,1.37773,7.2158,978.000000,4902.250000,7.84857,417.908997,15562.000000,...,1.42485,18.297100,11.26974,1.00381,32.094002,38.200001,18.585699,0.89115,24530.0,1.02261
2022-10-23,1.56939,153.822098,5.1634,1.36462,7.2428,972.250000,4916.350098,7.84940,415.769989,15626.000000,...,1.41670,18.034700,11.19039,0.99788,32.180000,38.049999,18.554331,0.88147,24820.0,1.01419
2022-10-24,1.57996,154.570007,5.3070,1.36940,7.2629,983.000000,4978.250000,7.84970,418.880005,15585.000000,...,1.42137,18.408899,11.14358,0.99979,32.308998,38.169998,18.565701,0.88489,24830.0,1.01160

In [56]:
# Exportamos a excel
currencies.to_excel('TC mundial.xlsx', sheet_name='Monedas', na_rep='', float_format=None, columns=None, header=True, index=True, index_label=None, startrow=0, startcol=0, engine=None, merge_cells=True, inf_rep='inf', freeze_panes=None, storage_options=None)